version: "3.7"

services:
  web:
    container_name: contactApi
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - 5000:5000
    command: npm run start:dev

  db:
    image: mongo:latest
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - dbdata-volume:/database/mongo.ts
    environment:
      MONGO_INITDB_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}

volumes:
  dbdata-volume:
